const first = {
  name: "first",
  size: [13, 13],
  solution: [
    "......R......",
    ".....FUN.....",
    "....SALES....",
    "...RECEIPT...",
    "..MERE.FARM..",
    ".DOVE...RAIL.",
    "MORE.....DRAW",
    ".HARD...TIED.",
    "..LION.SAND..",
    "...EVENING...",
    "....EVADE....",
    ".....ARE.....",
    "......D......"
  ],
  aQs: [
    ["FUN", "FUN (written in original grid)", 1, 5],
    ["SALES", "What bargain hunters enjoy", 2, 4],
    ["RECEIPT", "A written acknowledgment", 3, 3],
    ["MERE", "Such and nothing more", 4, 2],
    ["FARM", "To cultivate", 4, 7],
    ["DOVE", "A bird", 5, 1],
    ["RAIL", "A bar of wood or iron", 5, 8],
    ["MORE", "Opposed to less", 6, 0],
    ["DRAW", "What artists learn to do", 6, 9],
    ["HARD", "What this puzzle is", 7, 1],
    ["TIED", "Fastened", 7, 8],
    ["LION", "An animal of prey", 8, 2],
    ["SAND", "Found on the seashore", 8, 7],
    ["EVENING", "The close of day", 9, 3],
    ["EVADE", "To elude", 10, 4],
    ["ARE", "The plural of is", 11, 5]
  ],
  dQs: [
    ["RULE", "To govern", 0, 6],
    ["FACE", "Part of your head", 1, 5],
    ["NEIF", "A fist", 1, 7],
    ["SERE", "A talon", 2, 4],
    ["SPAR", "Part of a ship", 2, 8],
    ["REVERIE", "A day dream", 3, 3],
    ["TRADING", "Exchanging", 3, 9],
    ["MORAL", "What we all should be", 4, 2],
    ["MIRED", "To sink in mud", 4, 10],
    ["DOH", "The fibre of the gomuti plant", 5, 1],
    ["LAD", "A boy", 5, 11],
    ["DOVE", "A pigeon", 7, 4],
    ["TANE", "One", 7, 8],
    ["NEVA", "A river in Russia", 8, 5],
    ["SIDE", "To agree with", 8, 7],
    ["NARD", "An aromatic plant", 9, 6]
  ]
};

const tribute = {
  name: "tribute",
  size: [13, 13],
  solution: [
    "......C......",
    ".....FUN.....",
    "....DUROC....",
    "...MONDALE...",
    "..WELD.HALF..",
    ".MYST...WAIT.",
    "BANS.....TRIG",
    ".ENID...VISE.",
    "..EARS.SOOT..",
    "...HAIRPIN...",
    "....BAAED....",
    ".....NYC.....",
    "......S......"
  ],
  aQs: [
    ["FUN", "What this puzzle is (hopefully)", 1, 5],
    ["DUROC", "A breed of pig", 2, 4],
    ["MONDALE", "Carter's vice-president", 3, 3],
    ["WELD", "???", 4, 2],
    ["HALF", "???", 4, 7],
    ["MYST", "Seminal adventure puzzle video game", 5, 1],
    ["WAIT", "???", 5, 8],
    ["BANS", "???", 6, 0],
    ["TRIG", "???", 6, 9],
    ["ENID", "???", 7, 1],
    ["VISE", "???", 7, 8],
    ["EARS", "???", 8, 2],
    ["SOOT", "???", 8, 7],
    ["HAIRPIN", "???", 9, 3],
    ["BAAED", "Imitated a sheep", 10, 4],
    ["NYC", "???", 11, 5]
  ],
  dQs: [
    ["CURD", "", 0, 6],
    ["FUND", "", 1, 5],
    ["NOAH", "Of ark fame", 1, 7],
    ["DOLT", "", 2, 4],
    ["CLAW", "A talon", 2, 8],
    ["MESSIAH", "'He's not the _____, he's a very naughty boy", 3, 3],
    ["ELATION", "", 3, 9],
    ["WYNNE", "", 4, 2],
    ["FIRST", "", 4, 10],
    ["MAE", "", 5, 1],
    ["TIE", "A type of fighter in Star Wars", 5, 11],
    ["DRAB", "", 7, 4],
    ["VOID", "", 7, 8],
    ["SIAN", "", 8, 5],
    ["SPEC", "", 8, 7],
    ["RAYS", "", 9, 6]
  ]
};

export const puzzles = [first];
