meta_title: "Rob Owen King · Personal Site"
meta_description: "Hi, I'm Rob Owen King, programmer, polyglot and puzzle fan. This is my site."
meta_image: "profile_pic_jamesnic_cropped.jpg" # should exist in `app/assets/images/`
twitter_account: "@RobOwenKing"   # required for Twitter Cards
